### ISSUE TITLE
Raw SQL in app.py 

### ISSUE THREAD

**Issue by prateekj117** [SUMSarizer/SUMSarizer#47]
I found some raw SQL in app.py which I think should be converted to SQLAlchemy as it makes data access more abstract and portable.

**Comment by marcpare** [comment]
Hi @prateekj117, please be more specific with what you are referring to. The raw sql I can remember being in this app is there for performance reasons.

**Comment by prateekj117** [comment]
![screenshot from 2018-03-15 16-00-38](https://user-images.githubusercontent.com/31065687/37458188-3ce34b36-286a-11e8-949e-33c64c0eb258.png)

This is the raw SQL part I am talking about. I think it should be converted to SQLAlchemy.

**Comment by marcpare** [comment]
Thanks for your input, but if you check out the git blame for that line, it was converted to raw SQL for performance reasons.

Anyway, more "abstract and portable" is too vague of a benefit to be worth the trouble. It's pretty readable as is. There are a lot more valuable things to spend time improving in this app than this!

Next time, please link to the raw number rather than use a screenshot
https://stackoverflow.com/questions/23821235/how-to-link-to-specific-line-number-on-github

**Comment by prateekj117** [comment]
Okay, thanks a lot for advice.
